sudo: false

language: php

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  include:
    - php: 5.6
      env:
        - CS_CHECK=true
    - php: 7.0
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer test
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

notifications:
  email: true